Repository FES10-8-2/vanilla-project, pull requests merged in 2024-07, with the labels that each got.

#8 pull_request 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🛠기능 구현

#11 충돌 해결해보기
  README.md
Labels: wontfix

#12 리드미 수정
  README.md
Labels: 버그 수정
